### ISSUE TITLE
nav bar와 일부 html파일 관련 이슈

### ISSUE THREAD

**Issue by codingbowoo** [Ofgirls/ofgirlskorea#1]
![image](https://user-images.githubusercontent.com/11171902/31233249-2092bcf8-aa27-11e7-8110-c56d037778da.png)

전체 화면으로 했을 때  앞쪽 padding 이 달라서 요상하게 보이는 것 같아요 

@huhint  html 파일의 해당 css에  앞쪽 padding을 주는 편이 자연스러울 것 같습니다
@dhdh6190  아니면 nav bar에서 로고의 위치가 리액티브할 수 있을까요?!
--> 는 이미 리액티브 하네용.. 전체화면일 때 위치에 대한 둘의 토론이 필요할 것 같아요

**Comment by huhint** [comment]
bamboo.css에서
.container 클래스에서 이미 padding을 주었는데 왜 적용이 안되는지 모르겠어요.
확인해볼게요.

**Comment by soohuh620** [comment]
프로젝트 파일 내에 
bamboo > static > css > bamboo.css와
reprot > static > css > bamboo.css가 존재해서 혼동이 온 것 같습니다. 

도현 씨가 고치는 중.

**Comment by ddyokim** [comment]
저거 nav bar 코드 밑에 container div에 content 라는 class가 중복으로 들어가있어서 그렇습니다! 해결완료!
`<div class="content container">  --> <div class="container">`
