### ISSUE TITLE
제가 GLYPHICONS에서 아이콘을 따왔는데....

### ISSUE THREAD

**Issue by codingbowoo** [Ofgirls/ofgirlskorea#5]
GLYPHICONS FREE license

are released under the Creative Commons Attribution 3.0 Unported (CC BY 3.0). The GLYPHICONS FREE can be used both commercially and for personal use, but you must always add a link to GLYPHICONS.com in a prominent place (e.g. the footer of a website), include the CC-BY license and the reference to GLYPHICONS.com on every page using icons.

If you want to use the icons without restrictions, please support me by buying any version of icons on GLYPHICONS.com

GLYPHICONS FREE는 라이선스가 있어서 footer에 추가하고 명시해줘야 하고, 사실 opensource project에 쓰지 말라고 했음. (아래 이미지 참고) 저기서 말하는 opensource project가 뭘 말하는 걸까요? djangogirlstutorial도 opensource project 아닝가... 대체할만한 icon 모음 website를 우선 찾아볼게요. 

![image](https://user-images.githubusercontent.com/11171902/31307214-11760c60-ab9a-11e7-833c-a87bdc1304d3.png)

**Comment by codingbowoo** [comment]
@dhdh6190  도현맨도 glyphicon에서 아이콘 따왔더라....!

**Comment by ddyokim** [comment]
오잉 나 저거 [bootstrap](https://getbootstrap.com/docs/3.3/components/#glyphicons)에서 제공한다길래 그냥 썼는데!(놀람) 라이센스를 표시해줘야하는구나!

**Comment by huhint** [comment]
라이센스만 표시하면 문제될 것 없어 보이는 걸! Readme.md에도 이따가 추가할게요.
